[package]
name = "ipinfo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.20", features = ["json", "blocking"] }
serde = { version = "1.0.168", features = ["derive"] }
tabled = "0.14.0"
thiserror = "1.0.48"

[dev-dependencies]
mockito = "1.1.0"
